const data = [{
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Vans",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Puma",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Puma",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Asisc",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Nike",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "H&M",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Asisc",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "H&M",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Shoes",
        brand: "H&M",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Asisc",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Prada",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "10.00",
    },
    {
        type: "Shoes",
        brand: "Vans",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "8.99",
    },
    {
        type: "Shoes",
        brand: "Levi's",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Puma",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Vans",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Nike",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "24.99",
    },
    {
        type: "Hat",
        brand: "Outhorn",
        picture: "img/outhornHat.png",
        rating: "&#9733; &#9733; &#9733; &#9734; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "11.38",
    },
    {
        type: "Hoodie",
        brand: "S.O.A.",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "37.49",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Jacket",
        brand: "H&M",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "32.00",
    },
    {
        type: "Jacket",
        brand: "H&M",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "32.00",
    },
];