const data = [{
        type: "Shoes",
        brand: "Adidas",
        picture: "img/adidasShoesSnickers_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "21.99",
    },
    {
        type: "T-Shirt",
        brand: "Vans",
        picture: "img/vansTshirt_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "9.95",
    },
    {
        type: "Shoes",
        brand: "Puma",
        picture: "img/pumaShoes_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "12.45",
    },
    {
        type: "Hat",
        brand: "Adidas",
        picture: "img/adidasHat_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "4.79",
    },
    {
        type: "Backpack",
        brand: "Adidas",
        picture: "img/adidasBackpack_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "6.49",
    },
    {
        type: "Tshirt",
        brand: "Puma",
        picture: "img/pumaTshirt_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "15.00",
    },
    {
        type: "Gymbag",
        brand: "Adidas",
        picture: "img/adidasGymBag_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "12.99",
    },
    {
        type: "Hoodie",
        brand: "H&m",
        picture: "img/hmHoodieBoy_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "27.45",
    },
    {
        type: "Shoes",
        brand: "Adidas",
        picture: "img/adidasShoesRed_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "16.30",
    },
    {
        type: "Tracksuit",
        brand: "Adidas",
        picture: "img/adidasTracksuit_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "22.00",
    },
    {
        type: "Jacket",
        brand: "Zara",
        picture: "img/zaraBomberjacket_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "34.79",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/zaraHighheel_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "29.99",
    },
    {
        type: "Pants",
        brand: "Asisc",
        picture: "img/ascTightsPants_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "7.45",
    },
    {
        type: "Tracksuit",
        brand: "Adidas",
        picture: "img/adidasTracksuitPants_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "14.98",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/zaraBoots_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "12.20",
    },
    {
        type: "Jacket",
        brand: "Zara",
        picture: "img/zaraFlightjacket_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "26.78",
    },
    {
        type: "Shoes",
        brand: "Nike",
        picture: "img/nikeShoes.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "18.80",
    },
    {
        type: "Hoodie",
        brand: "H&M",
        picture: "img/hmHoodieGirl_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "31.90",
    },
    {
        type: "Shoes",
        brand: "Asisc",
        picture: "img/ascShoesTct_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "12.00",
    },
    {
        type: "Jacket",
        brand: "Nike",
        picture: "img/nikeJacket_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "26.10",
    },
    {
        type: "Hat",
        brand: "Pull&Bear",
        picture: "img/p&bBuckethat_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "10.00",
    },
    {
        type: "Hoodie",
        brand: "Pull&Bear",
        picture: "img/p&bHoodie_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "38.21",
    },
    {
        type: "Jacket",
        brand: "Pull&Bear",
        picture: "img/p&bJacket_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.89",
    },
    {
        type: "Pants",
        brand: "Pull&Bear",
        picture: "img/p&bTrousers_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "38.98",
    },
    {
        type: "Sweater",
        brand: "H&M",
        picture: "img/hmSweater_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "16.19",
    },
    {
        type: "Shoes",
        brand: "Zara",
        picture: "img/zaraSafetyshoes_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "8.99",
    },
    {
        type: "Shoes",
        brand: "Asisc",
        picture: "img/ascShoesBlue_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "19.99",
    },
    {
        type: "Shoes",
        brand: "Prada",
        picture: "img/pradaSunglasses_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "23.45",
    },
    {
        type: "Hoodie",
        brand: "Nike",
        picture: "img/nikeHoodie_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "39.00",
    },
    {
        type: "Hoodie",
        brand: "Vans",
        picture: "img/vansHoodie_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "18.89",
    },
    {
        type: "Shoes",
        brand: "Levi's",
        picture: "img/levisJacket1_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "27.23",
    },
    {
        type: "Hat",
        brand: "Puma",
        picture: "img/pumaHat_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "15.35",
    },
    {
        type: "Pants",
        brand: "Zara",
        picture: "img/zaraTrousers_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "28.89",
    },
    {
        type: "Shoes",
        brand: "Vans",
        picture: "img/vansClassic_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "22.99",
    },
    {
        type: "Hat",
        brand: "Nike",
        picture: "img/nikeHat_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "24.99",
    },
    {
        type: "Hat",
        brand: "Outhorn",
        picture: "img/outhornHat.png",
        rating: "&#9733; &#9733; &#9733; &#9734; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "11.38",
    },
    {
        type: "Hoodie",
        brand: "S.O.A.",
        picture: "img/soaHoodie.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "45.49",
    },
    {
        type: "Tshirt",
        brand: "Pull&Bear",
        picture: "img/p&bTshirt_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9734;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "20.00",
    },
    {
        type: "Jumpsuit",
        brand: "H&M",
        picture: "img/hmJumpsuit_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "32.00",
    },
    {
        type: "Jacket",
        brand: "H&M",
        picture: "img/hmJacketGirl_t.png",
        rating: "&#9733; &#9733; &#9733; &#9733; &#9733;",
        description: "Description Lorem ipsum dolor sit amet consectetur.",
        price: "32.00",
    },
];